djangoFirstProjects/Airbnb/urls.py
from django.urls import path
from . import views

app_name = "Airbnb"
urlpatterns = [

     path("", views.index, name="Index"),
     path("/search", views.showAvailable, name="List"),
     path("/<int:pk>", views.ShowProperty, name="Detail"),
     path("/<int:idProperty>/reserve", views.ReserveProperty, name="Reserve"),
    # path("", views.CityList.as_view(), name="List"),
    # path("<int:pk>", views.CityDetail.as_view(), name="Detail"),

]

djangoFirstProjects/djangoFirstProjects/urls.py
from django.contrib import admin
from django.urls import path, include
from . import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Airbnb.urls")),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djangoFirstProjects/Airbnb/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.admin import admin
from django.utils import timezone
from django.contrib.admin.models import LogEntry, ADDITION
from django.contrib.contenttypes.models import ContentType
from django.core.validators import MinValueValidator


# Create your models here.


class City(models.Model):
    name = models.CharField(max_length=50, default="No name provided")

    def __str__(self):
        return "This is the city: " + self.name


class Property(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.ForeignKey(City, on_delete=models.PROTECT)
    tittle = models.CharField(max_length=60)
    description = models.CharField(max_length=500)
    pricePerDay = models.FloatField(default=0.0, validators=[MinValueValidator(0.0)])
    maxPeople = models.IntegerField(validators=[MinValueValidator(0.0)])
    photo = models.ImageField(upload_to="gallery")

    def __str__(self):
        return self.tittle


class Reservation(models.Model):
    property = models.ForeignKey(Property, on_delete=models.PROTECT)
    date = models.DateField(default=timezone.now())
    code = models.CharField(max_length=70, default=str(timezone.now()))
    subtotal = models.FloatField(default=0.0)
    commission = models.FloatField(default=0.0)
    total = models.FloatField(default=0.0)
    guestName = models.CharField(max_length=50)
    guestLastName = models.CharField(max_length=50)
    guestEmail = models.EmailField()

    def __str__(self):
        return self.code


class DateRental(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name="dates")
    reservation = models.ForeignKey(Reservation, null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)


class DateRentalInline(admin.TabularInline):
    model = DateRental
    fk_name = "property"
    max_num = 7


class PropertyAdmin(admin.ModelAdmin):
    fields = ('city', 'tittle', 'description', 'pricePerDay', 'maxPeople', 'photo')
    inlines = [DateRentalInline, ]

    def get_queryset(self, request):
        qs = super(PropertyAdmin, self).get_queryset(request)
        if request.user.is_superuser:
            return qs
        property_ct = ContentType.objects.get_for_model(Property)
        log_entries = LogEntry.objects.filter(
            content_type=property_ct,
            user=request.user,
            action_flag=ADDITION
        )
        user_property_ids = [a.object_id for a in log_entries]
        return qs.filter(id__in=user_property_ids)

    def save_model(self, request, instance, form, change):
        instance.owner = request.user
        super(PropertyAdmin, self).save_model(request, instance, form, change)

djangoFirstProjects/Airbnb/forms.py
# from django import forms
#
#
# class CityAddForm(forms.Form):
#     name = forms.CharField()

djangoFirstProjects/Airbnb/views.py
from datetime import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import generic
from django.views.decorators.csrf import csrf_exempt

from . import models


def index(request):
    return render(request, "Airbnb/welcome.html", {"cities": models.City.objects.all()})


@csrf_exempt
def showAvailable(request):
    fromDate = request.POST['dateFrom']
    toDate = request.POST['dateTo']
    date_format = "%Y-%m-%d"
    a = datetime.strptime(fromDate, date_format)
    b = datetime.strptime(toDate, date_format)

    days = (b - a).days + 1
    properties = []

    maxPax = request.POST["maxPax"]
    city = request.POST["city"]

    for property in models.Property.objects.filter(maxPeople__gte=maxPax, city__id=city):
        if property.dates.filter(date__range=[fromDate, toDate], reservation=None).count() == days:
            properties.append(property)

    return render(request, "Airbnb/index2.html",
                  {"properties": properties, "from": fromDate, "to": toDate, "max": maxPax,
                   "cities": models.City.objects.all().exclude(pk=city), "selected": models.City.objects.get(pk=city)})


def ShowProperty(request, pk):
    fromDate = request.POST['dateFrom']
    toDate = request.POST['dateTo']
    date_format = "%Y-%m-%d"
    a = datetime.strptime(fromDate, date_format)
    b = datetime.strptime(toDate, date_format)

    days = (b - a).days + 1
    obj = get_object_or_404(models.Property, pk=pk)

    subtotal = days * obj.pricePerDay
    comision = subtotal * 0.08
    total = subtotal + comision

    return render(request, "Airbnb/detail.html",
                  {"object": obj, "from": fromDate, "to": toDate, "idProperty": pk, "subtotal": subtotal,
                   "comision": comision, "total": total})


def ReserveProperty(request, idProperty):
    print(request.POST)
    data = request.POST
    property = models.Property.objects.get(pk=idProperty)
    reservation = models.Reservation(property=property, subtotal=data['subtotal'], commission=data['comission'],
                                     total=data['total'], guestName=data['guestName'],
                                     guestLastName=data['guestLastName'], guestEmail=data['guestEmail'])

    reservation.save()

    datesSelected = property.dates.filter(date__range=[data['dateFrom'], data['dateTo']], reservation=None)

    for date in datesSelected:
        date.reservation = reservation
        date.save()

    return render(request, "Airbnb/welcome.html", {"cities": models.City.objects.all(), "message" : "Thank you for your reservation!"})

djangoFirstProjects/Airbnb/templates/Airbnb/base2.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reservation - UTN</title>
  
</head>

<body background="{% static 'Airbnb/images/fondo.jpg' %}">

    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="{% url 'Airbnb:Index' %}">Reservation</a>
    </nav>


    {%block content%}{% endblock %}

    <div class="my-4 py-4"> </div>
    <div class="my-5 py-4"> </div>
    
    <footer class="fixed-bottom border border-white" >
        <div class="container-fluid bg-dark">
            

                <img class="img-fluid" src="{% static 'Airbnb/images/rociofooter.png' %}" alt="Loading footer..." weight="100%" height="auto">
                
        </div>

    </footer>
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
        integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
        crossorigin="anonymous"></script>




</body>

</html>

djangoFirstProjects/Airbnb/templates/Airbnb/detail.html
{% extends "Airbnb/base2.html" %}
{% load static %}
{% block content %}

<section>
    <div class="container-fluid  pt-3  bg-secondary">


        <div class="jumbotron p-2 p-md-5 text-white rounded bg-dark">
            <p> <img class="img-fluid" src="{{object.photo.url}}" width="100%" height="auto">
            <div class="d-flex">
                <div class="col-md-6 px-0">
                    <h2 class="display-4 font-italic">{{object.tittle}}</h2>
                    <p class="lead my-3">Max pax: {{object.maxPeople}}</p>
                    <p class="lead my-3">{{object.description}}</p>
                </div>
                <div class="col-md-6 px-0">
                    <h4 class="mb-3">Form Rental</h4>
                    <form class="mb-5" method="post" action="{% url 'Airbnb:Reserve' object.id %}">
                        {% csrf_token %}
                        <div class="row">
                            <!-- <input disabled class="d-none" type="number" id="idProperty" name="idProperty" value="{{idProperty}}"> -->
                            <input class="d-none" type="date" id="dateFrom" name="dateFrom" value="{{from}}">
                            <input class="d-none" type="date" id="dateTo" name="dateTo" value="{{to}}">

                        </div>

                        <div class="row">
                            <div class="col-md-6 mb-3">

                                <label for="pricePerDAy">Price per day</label>
                                <input readonly type="text" class="form-control" id="pricePerDAy"
                                    value="{{object.pricePerDay}}">
                            </div>
                            <div class="col-md-6 mb-3">

                                <label for="comission">Comission (8%)</label>
                                <input readonly type="text" class="form-control" id="comission" name="comission"
                                    value="{{comision}}">
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-6 mb-3">

                                <label for="subtotal">Subtotal</label>
                                <input readonly type="text" class="form-control" id="subtotal" name="subtotal"
                                    value="{{subtotal}}">
                            </div>
                            <div class="col-md-6 mb-3">

                                <label for="total">Total</label>
                                <input readonly type="text" class="form-control" id="total" name="total"
                                    value="{{total}}">
                            </div>

                        </div>
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="firstName">First name</label>
                                <input type="text" class="form-control" id="firstName" placeholder="First Name"
                                    name="guestName" value="" required>
                                <div class="invalid-feedback">
                                    Valid first name is required.
                                </div>
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="lastName">Last name</label>
                                <input type="text" class="form-control" id="lastName" placeholder="Last Name"
                                    name="guestLastName" value="" required>
                                <div class="invalid-feedback">
                                    Valid last name is required.
                                </div>
                            </div>
                        </div>

                        <div class="mb-3">
                            <label for="email">Email</label>
                            <input required type="email" class="form-control" id="email" placeholder="you@example.com"
                                name="guestEmail">
                            <div class="invalid-feedback">
                                Please enter a valid email address for shipping updates.
                            </div>
                        </div>


                        <hr class="mb-4">

                        <button class="btn btn-primary btn-lg btn-block" type="submit">Continue to checkout</button>
                    </form>
                </div>

            </div>
        </div>




    </div>

</section>

{% endblock %}

djangoFirstProjects/Airbnb/templates/Airbnb/index2.html
{% extends "Airbnb/base2.html" %}
{% load static %}
{% block content %}
<div class="container p-3 ">
    <form class=" form-inline border border-dark p-4 rounded col-md-6 d-flex flex-wrap bg-light " method="post"
        action="{% url 'Airbnb:List' %}" class="">
        <div class="form-group  d-flex flex-wrap">
            <label for="dateFrom">From</label>
            <input class="mx-2 bg-light " type="date" id="dateFrom" name="dateFrom" value="{{from}}">
            <label for="dateTo">To</label>
            <input class="mx-2 bg-light " type="date" id="dateTo" name="dateTo" value="{{to}}">
        </div>

        <div class="form-group d-flex flex-wrap">
            <button class="btn btn-dark" type="submit">Search</button>
        </div>

        <!-- parte nueva  -->
        <div class="form-group d-flex flex-wrap">
            <label for="city">City: </label>

            <select name="city" id="city" required class="mx-2 p-1">
                
                {% if selected%}
                <option value="{{selected.id}}">{{selected.name}}</option>
                {% endif %}
                {% for city in cities %}
                <option value="{{city.id}}">{{city.name}}</option>
                {% endfor %}
            </select>
            <label for="maxPax">Max Pax:</label>
            <input class="from-control mx-2" value="{{max}}" required type="number" step="1" min="1" name="maxPax" id="maxPax">
        </div>  
        <!-- fin parte nueva  -->
    </form>

    <div class="d-flex flex-wrap">
        {% if not properties%}

        <div class="alert alert-danger my-5" role="alert">
            Ups! It seems there are no properties available. Try other dates/city/pax.
        </div>

        {% endif %}
        {% for i in properties %}

        <div class="card m-4" style="width: 18rem;">
            <img src="{{i.photo.url }}" class="img-fluid card-img-top" alt="Loading...">
            <div class="card-body">
                <h5 class="card-title">{{i.tittle}}</h5>
                <form action="{% url 'Airbnb:Detail' i.id %}" method="post">{% csrf_token %}

                    <input class="d-none" type="date" id="dateFrom" name="dateFrom" value="{{from}}">
                    <input class="d-none" type="date" id="dateTo" name="dateTo" value="{{to}}">
                    <button class="btn btn-dark" type="submit">Rental</button>
                </form>
            </div>
        </div>

        {% endfor %}

    </div>


</div>
<script>
    (function () {
        const dFrom = document.getElementById("dateFrom");
        const dTo = document.getElementById("dateTo");


        dFrom.min =  new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().split("T")[0];

        dFrom.addEventListener("change", () => { dTo.value = ""; dTo.min = dFrom.value; }, false);


    })();

</script>
{% endblock %}

djangoFirstProjects/Airbnb/templates/Airbnb/welcome.html
{% extends "Airbnb/base2.html" %}
{% load static %}
{% block content %}


<div class="container-fluid  py-3 ">

    {% if message %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    {% endif %}
    <div class="alert alert-success text-center" role="alert">
        <h4 class="alert-heading"></h4>
        Welcome, please indicate your dates!
    </div>


    <form class="form-inline border border-dark p-4 rounded col-md-6 d-flex flex-wrap bg-light " method="post"
        action="{% url 'Airbnb:List' %}" class="">
        <div class="form-group  d-flex flex-wrap">
            <label for="dateFrom">From</label>
            <input class="mx-2 bg-light " type="date" id="dateFrom" required name="dateFrom">
            <label for="dateTo">To</label>
            <input class="mx-2 bg-light " type="date" id="dateTo" required name="dateTo">
        </div>

        <div class="form-group d-flex flex-wrap">

            <button class="btn btn-dark" type="submit">Search</button>

        </div>

        <!-- parte nueva  -->
        <div class="form-group d-flex flex-wrap p-1">
            <label for="city">City: </label>

            <select name="city" id="city" required class="mx-2  ">

                {% for city in cities %}
                <option value="{{city.id}}">{{city.name}}</option>
                {% endfor %}
            </select>
            <label for="maxPax">Pax: </label>
            <input class="from-control mx-2" required type="number" step="1" min="1" name="maxPax" id="maxPax">
        </div>
        <!-- fin parte nueva  -->

    </form>
</div>
<script>
    (function () {
        const dFrom = document.getElementById("dateFrom");
        const dTo = document.getElementById("dateTo");


        dFrom.min =  new Date(new Date().getTime() - new Date().getTimezoneOffset() * 60000).toISOString().split("T")[0];

        dFrom.addEventListener("change", () => { dTo.value = ""; dTo.min = dFrom.value; }, false);


    })();

</script>
{% endblock %}